/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/boardStates": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.boardStates.id"];
          boardId?: parameters["rowFilter.boardStates.boardId"];
          description?: parameters["rowFilter.boardStates.description"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["boardStates"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** boardStates */
          boardStates?: definitions["boardStates"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.boardStates.id"];
          boardId?: parameters["rowFilter.boardStates.boardId"];
          description?: parameters["rowFilter.boardStates.description"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.boardStates.id"];
          boardId?: parameters["rowFilter.boardStates.boardId"];
          description?: parameters["rowFilter.boardStates.description"];
        };
        body: {
          /** boardStates */
          boardStates?: definitions["boardStates"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/boards": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.boards.id"];
          created_at?: parameters["rowFilter.boards.created_at"];
          teamId?: parameters["rowFilter.boards.teamId"];
          name?: parameters["rowFilter.boards.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["boards"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** boards */
          boards?: definitions["boards"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.boards.id"];
          created_at?: parameters["rowFilter.boards.created_at"];
          teamId?: parameters["rowFilter.boards.teamId"];
          name?: parameters["rowFilter.boards.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.boards.id"];
          created_at?: parameters["rowFilter.boards.created_at"];
          teamId?: parameters["rowFilter.boards.teamId"];
          name?: parameters["rowFilter.boards.name"];
        };
        body: {
          /** boards */
          boards?: definitions["boards"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/chatMembers": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.chatMembers.id"];
          userId?: parameters["rowFilter.chatMembers.userId"];
          chatId?: parameters["rowFilter.chatMembers.chatId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["chatMembers"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** chatMembers */
          chatMembers?: definitions["chatMembers"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.chatMembers.id"];
          userId?: parameters["rowFilter.chatMembers.userId"];
          chatId?: parameters["rowFilter.chatMembers.chatId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.chatMembers.id"];
          userId?: parameters["rowFilter.chatMembers.userId"];
          chatId?: parameters["rowFilter.chatMembers.chatId"];
        };
        body: {
          /** chatMembers */
          chatMembers?: definitions["chatMembers"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/chats": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.chats.id"];
          createdAt?: parameters["rowFilter.chats.createdAt"];
          isGroup?: parameters["rowFilter.chats.isGroup"];
          name?: parameters["rowFilter.chats.name"];
          description?: parameters["rowFilter.chats.description"];
          thumbnail?: parameters["rowFilter.chats.thumbnail"];
          teamId?: parameters["rowFilter.chats.teamId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["chats"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** chats */
          chats?: definitions["chats"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.chats.id"];
          createdAt?: parameters["rowFilter.chats.createdAt"];
          isGroup?: parameters["rowFilter.chats.isGroup"];
          name?: parameters["rowFilter.chats.name"];
          description?: parameters["rowFilter.chats.description"];
          thumbnail?: parameters["rowFilter.chats.thumbnail"];
          teamId?: parameters["rowFilter.chats.teamId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.chats.id"];
          createdAt?: parameters["rowFilter.chats.createdAt"];
          isGroup?: parameters["rowFilter.chats.isGroup"];
          name?: parameters["rowFilter.chats.name"];
          description?: parameters["rowFilter.chats.description"];
          thumbnail?: parameters["rowFilter.chats.thumbnail"];
          teamId?: parameters["rowFilter.chats.teamId"];
        };
        body: {
          /** chats */
          chats?: definitions["chats"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/estimations": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.estimations.id"];
          created_at?: parameters["rowFilter.estimations.created_at"];
          effort?: parameters["rowFilter.estimations.effort"];
          userId?: parameters["rowFilter.estimations.userId"];
          justification?: parameters["rowFilter.estimations.justification"];
          taskId?: parameters["rowFilter.estimations.taskId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["estimations"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** estimations */
          estimations?: definitions["estimations"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.estimations.id"];
          created_at?: parameters["rowFilter.estimations.created_at"];
          effort?: parameters["rowFilter.estimations.effort"];
          userId?: parameters["rowFilter.estimations.userId"];
          justification?: parameters["rowFilter.estimations.justification"];
          taskId?: parameters["rowFilter.estimations.taskId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.estimations.id"];
          created_at?: parameters["rowFilter.estimations.created_at"];
          effort?: parameters["rowFilter.estimations.effort"];
          userId?: parameters["rowFilter.estimations.userId"];
          justification?: parameters["rowFilter.estimations.justification"];
          taskId?: parameters["rowFilter.estimations.taskId"];
        };
        body: {
          /** estimations */
          estimations?: definitions["estimations"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/initiatives": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.initiatives.id"];
          created_at?: parameters["rowFilter.initiatives.created_at"];
          title?: parameters["rowFilter.initiatives.title"];
          description?: parameters["rowFilter.initiatives.description"];
          content?: parameters["rowFilter.initiatives.content"];
          teamId?: parameters["rowFilter.initiatives.teamId"];
          dueDate?: parameters["rowFilter.initiatives.dueDate"];
          owner?: parameters["rowFilter.initiatives.owner"];
          status?: parameters["rowFilter.initiatives.status"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["initiatives"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** initiatives */
          initiatives?: definitions["initiatives"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.initiatives.id"];
          created_at?: parameters["rowFilter.initiatives.created_at"];
          title?: parameters["rowFilter.initiatives.title"];
          description?: parameters["rowFilter.initiatives.description"];
          content?: parameters["rowFilter.initiatives.content"];
          teamId?: parameters["rowFilter.initiatives.teamId"];
          dueDate?: parameters["rowFilter.initiatives.dueDate"];
          owner?: parameters["rowFilter.initiatives.owner"];
          status?: parameters["rowFilter.initiatives.status"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.initiatives.id"];
          created_at?: parameters["rowFilter.initiatives.created_at"];
          title?: parameters["rowFilter.initiatives.title"];
          description?: parameters["rowFilter.initiatives.description"];
          content?: parameters["rowFilter.initiatives.content"];
          teamId?: parameters["rowFilter.initiatives.teamId"];
          dueDate?: parameters["rowFilter.initiatives.dueDate"];
          owner?: parameters["rowFilter.initiatives.owner"];
          status?: parameters["rowFilter.initiatives.status"];
        };
        body: {
          /** initiatives */
          initiatives?: definitions["initiatives"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/messages": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.messages.id"];
          createdAt?: parameters["rowFilter.messages.createdAt"];
          text?: parameters["rowFilter.messages.text"];
          chatId?: parameters["rowFilter.messages.chatId"];
          userId?: parameters["rowFilter.messages.userId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["messages"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** messages */
          messages?: definitions["messages"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.messages.id"];
          createdAt?: parameters["rowFilter.messages.createdAt"];
          text?: parameters["rowFilter.messages.text"];
          chatId?: parameters["rowFilter.messages.chatId"];
          userId?: parameters["rowFilter.messages.userId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.messages.id"];
          createdAt?: parameters["rowFilter.messages.createdAt"];
          text?: parameters["rowFilter.messages.text"];
          chatId?: parameters["rowFilter.messages.chatId"];
          userId?: parameters["rowFilter.messages.userId"];
        };
        body: {
          /** messages */
          messages?: definitions["messages"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/options": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.options.id"];
          initiativeId?: parameters["rowFilter.options.initiativeId"];
          content?: parameters["rowFilter.options.content"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["options"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** options */
          options?: definitions["options"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.options.id"];
          initiativeId?: parameters["rowFilter.options.initiativeId"];
          content?: parameters["rowFilter.options.content"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.options.id"];
          initiativeId?: parameters["rowFilter.options.initiativeId"];
          content?: parameters["rowFilter.options.content"];
        };
        body: {
          /** options */
          options?: definitions["options"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/organizationInvitations": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.organizationInvitations.id"];
          createdAt?: parameters["rowFilter.organizationInvitations.createdAt"];
          userEmail?: parameters["rowFilter.organizationInvitations.userEmail"];
          organizationId?: parameters["rowFilter.organizationInvitations.organizationId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["organizationInvitations"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** organizationInvitations */
          organizationInvitations?: definitions["organizationInvitations"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.organizationInvitations.id"];
          createdAt?: parameters["rowFilter.organizationInvitations.createdAt"];
          userEmail?: parameters["rowFilter.organizationInvitations.userEmail"];
          organizationId?: parameters["rowFilter.organizationInvitations.organizationId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.organizationInvitations.id"];
          createdAt?: parameters["rowFilter.organizationInvitations.createdAt"];
          userEmail?: parameters["rowFilter.organizationInvitations.userEmail"];
          organizationId?: parameters["rowFilter.organizationInvitations.organizationId"];
        };
        body: {
          /** organizationInvitations */
          organizationInvitations?: definitions["organizationInvitations"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/organizationMembers": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.organizationMembers.id"];
          userId?: parameters["rowFilter.organizationMembers.userId"];
          organizationId?: parameters["rowFilter.organizationMembers.organizationId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["organizationMembers"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** organizationMembers */
          organizationMembers?: definitions["organizationMembers"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.organizationMembers.id"];
          userId?: parameters["rowFilter.organizationMembers.userId"];
          organizationId?: parameters["rowFilter.organizationMembers.organizationId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.organizationMembers.id"];
          userId?: parameters["rowFilter.organizationMembers.userId"];
          organizationId?: parameters["rowFilter.organizationMembers.organizationId"];
        };
        body: {
          /** organizationMembers */
          organizationMembers?: definitions["organizationMembers"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/organizations": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.organizations.id"];
          createdAt?: parameters["rowFilter.organizations.createdAt"];
          name?: parameters["rowFilter.organizations.name"];
          slug?: parameters["rowFilter.organizations.slug"];
          logoUrl?: parameters["rowFilter.organizations.logoUrl"];
          description?: parameters["rowFilter.organizations.description"];
          ownerId?: parameters["rowFilter.organizations.ownerId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["organizations"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** organizations */
          organizations?: definitions["organizations"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.organizations.id"];
          createdAt?: parameters["rowFilter.organizations.createdAt"];
          name?: parameters["rowFilter.organizations.name"];
          slug?: parameters["rowFilter.organizations.slug"];
          logoUrl?: parameters["rowFilter.organizations.logoUrl"];
          description?: parameters["rowFilter.organizations.description"];
          ownerId?: parameters["rowFilter.organizations.ownerId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.organizations.id"];
          createdAt?: parameters["rowFilter.organizations.createdAt"];
          name?: parameters["rowFilter.organizations.name"];
          slug?: parameters["rowFilter.organizations.slug"];
          logoUrl?: parameters["rowFilter.organizations.logoUrl"];
          description?: parameters["rowFilter.organizations.description"];
          ownerId?: parameters["rowFilter.organizations.ownerId"];
        };
        body: {
          /** organizations */
          organizations?: definitions["organizations"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profiles": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          createdAt?: parameters["rowFilter.profiles.createdAt"];
          email?: parameters["rowFilter.profiles.email"];
          firstName?: parameters["rowFilter.profiles.firstName"];
          lastName?: parameters["rowFilter.profiles.lastName"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profiles"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          createdAt?: parameters["rowFilter.profiles.createdAt"];
          email?: parameters["rowFilter.profiles.email"];
          firstName?: parameters["rowFilter.profiles.firstName"];
          lastName?: parameters["rowFilter.profiles.lastName"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          createdAt?: parameters["rowFilter.profiles.createdAt"];
          email?: parameters["rowFilter.profiles.email"];
          firstName?: parameters["rowFilter.profiles.firstName"];
          lastName?: parameters["rowFilter.profiles.lastName"];
        };
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/subscriptions": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.subscriptions.id"];
          createdAt?: parameters["rowFilter.subscriptions.createdAt"];
          organizationId?: parameters["rowFilter.subscriptions.organizationId"];
          product?: parameters["rowFilter.subscriptions.product"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["subscriptions"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** subscriptions */
          subscriptions?: definitions["subscriptions"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.subscriptions.id"];
          createdAt?: parameters["rowFilter.subscriptions.createdAt"];
          organizationId?: parameters["rowFilter.subscriptions.organizationId"];
          product?: parameters["rowFilter.subscriptions.product"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.subscriptions.id"];
          createdAt?: parameters["rowFilter.subscriptions.createdAt"];
          organizationId?: parameters["rowFilter.subscriptions.organizationId"];
          product?: parameters["rowFilter.subscriptions.product"];
        };
        body: {
          /** subscriptions */
          subscriptions?: definitions["subscriptions"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/tasks": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tasks.id"];
          created_at?: parameters["rowFilter.tasks.created_at"];
          name?: parameters["rowFilter.tasks.name"];
          description?: parameters["rowFilter.tasks.description"];
          dueDate?: parameters["rowFilter.tasks.dueDate"];
          asignee?: parameters["rowFilter.tasks.asignee"];
          stateId?: parameters["rowFilter.tasks.stateId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["tasks"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** tasks */
          tasks?: definitions["tasks"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tasks.id"];
          created_at?: parameters["rowFilter.tasks.created_at"];
          name?: parameters["rowFilter.tasks.name"];
          description?: parameters["rowFilter.tasks.description"];
          dueDate?: parameters["rowFilter.tasks.dueDate"];
          asignee?: parameters["rowFilter.tasks.asignee"];
          stateId?: parameters["rowFilter.tasks.stateId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.tasks.id"];
          created_at?: parameters["rowFilter.tasks.created_at"];
          name?: parameters["rowFilter.tasks.name"];
          description?: parameters["rowFilter.tasks.description"];
          dueDate?: parameters["rowFilter.tasks.dueDate"];
          asignee?: parameters["rowFilter.tasks.asignee"];
          stateId?: parameters["rowFilter.tasks.stateId"];
        };
        body: {
          /** tasks */
          tasks?: definitions["tasks"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/teamMembers": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.teamMembers.id"];
          teamId?: parameters["rowFilter.teamMembers.teamId"];
          userId?: parameters["rowFilter.teamMembers.userId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["teamMembers"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** teamMembers */
          teamMembers?: definitions["teamMembers"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.teamMembers.id"];
          teamId?: parameters["rowFilter.teamMembers.teamId"];
          userId?: parameters["rowFilter.teamMembers.userId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.teamMembers.id"];
          teamId?: parameters["rowFilter.teamMembers.teamId"];
          userId?: parameters["rowFilter.teamMembers.userId"];
        };
        body: {
          /** teamMembers */
          teamMembers?: definitions["teamMembers"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/teamRooms": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.teamRooms.id"];
          teamId?: parameters["rowFilter.teamRooms.teamId"];
          roomId?: parameters["rowFilter.teamRooms.roomId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["teamRooms"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** teamRooms */
          teamRooms?: definitions["teamRooms"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.teamRooms.id"];
          teamId?: parameters["rowFilter.teamRooms.teamId"];
          roomId?: parameters["rowFilter.teamRooms.roomId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.teamRooms.id"];
          teamId?: parameters["rowFilter.teamRooms.teamId"];
          roomId?: parameters["rowFilter.teamRooms.roomId"];
        };
        body: {
          /** teamRooms */
          teamRooms?: definitions["teamRooms"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/teams": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.teams.id"];
          createdAt?: parameters["rowFilter.teams.createdAt"];
          name?: parameters["rowFilter.teams.name"];
          slug?: parameters["rowFilter.teams.slug"];
          description?: parameters["rowFilter.teams.description"];
          organizationId?: parameters["rowFilter.teams.organizationId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["teams"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** teams */
          teams?: definitions["teams"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.teams.id"];
          createdAt?: parameters["rowFilter.teams.createdAt"];
          name?: parameters["rowFilter.teams.name"];
          slug?: parameters["rowFilter.teams.slug"];
          description?: parameters["rowFilter.teams.description"];
          organizationId?: parameters["rowFilter.teams.organizationId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.teams.id"];
          createdAt?: parameters["rowFilter.teams.createdAt"];
          name?: parameters["rowFilter.teams.name"];
          slug?: parameters["rowFilter.teams.slug"];
          description?: parameters["rowFilter.teams.description"];
          organizationId?: parameters["rowFilter.teams.organizationId"];
        };
        body: {
          /** teams */
          teams?: definitions["teams"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/votes": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.votes.id"];
          createdAt?: parameters["rowFilter.votes.createdAt"];
          optionId?: parameters["rowFilter.votes.optionId"];
          userId?: parameters["rowFilter.votes.userId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["votes"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** votes */
          votes?: definitions["votes"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.votes.id"];
          createdAt?: parameters["rowFilter.votes.createdAt"];
          optionId?: parameters["rowFilter.votes.optionId"];
          userId?: parameters["rowFilter.votes.userId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.votes.id"];
          createdAt?: parameters["rowFilter.votes.createdAt"];
          optionId?: parameters["rowFilter.votes.optionId"];
          userId?: parameters["rowFilter.votes.userId"];
        };
        body: {
          /** votes */
          votes?: definitions["votes"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  boardStates: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `boards.id`.<fk table='boards' column='id'/>
     */
    boardId?: number;
    /** Format: text */
    description?: string;
  };
  boards: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `teams.id`.<fk table='teams' column='id'/>
     */
    teamId?: number;
    /** Format: text */
    name?: string;
  };
  chatMembers: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: uuid */
    userId?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `chats.id`.<fk table='chats' column='id'/>
     */
    chatId?: number;
  };
  chats: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    createdAt?: string;
    /** Format: boolean */
    isGroup?: boolean;
    /** Format: text */
    name?: string;
    /** Format: text */
    description?: string;
    /** Format: text */
    thumbnail?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `teams.id`.<fk table='teams' column='id'/>
     */
    teamId?: number;
  };
  estimations: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: bigint */
    effort?: number;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `profiles.id`.<fk table='profiles' column='id'/>
     */
    userId?: string;
    /** Format: text */
    justification?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `tasks.id`.<fk table='tasks' column='id'/>
     */
    taskId?: number;
  };
  initiatives: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    title?: string;
    /** Format: text */
    description?: string;
    /** Format: text */
    content?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `teams.id`.<fk table='teams' column='id'/>
     */
    teamId?: number;
    /** Format: timestamp with time zone */
    dueDate?: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `profiles.id`.<fk table='profiles' column='id'/>
     */
    owner?: string;
    /**
     * Format: text
     * @default draft
     */
    status?: string;
  };
  messages: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    createdAt?: string;
    /** Format: text */
    text?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `chats.id`.<fk table='chats' column='id'/>
     */
    chatId?: number;
    /** Format: uuid */
    userId?: string;
  };
  options: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `initiatives.id`.<fk table='initiatives' column='id'/>
     */
    initiativeId?: number;
    /** Format: text */
    content?: string;
  };
  organizationInvitations: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    createdAt?: string;
    /** Format: character varying */
    userEmail?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `organizations.id`.<fk table='organizations' column='id'/>
     */
    organizationId?: number;
  };
  organizationMembers: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: uuid */
    userId?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `organizations.id`.<fk table='organizations' column='id'/>
     */
    organizationId?: number;
  };
  organizations: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    createdAt?: string;
    /** Format: text */
    name?: string;
    /** Format: text */
    slug?: string;
    /** Format: text */
    logoUrl?: string;
    /** Format: text */
    description?: string;
    /** Format: uuid */
    ownerId?: string;
  };
  profiles: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    createdAt?: string;
    /** Format: text */
    email: string;
    /** Format: text */
    firstName?: string;
    /** Format: text */
    lastName?: string;
  };
  subscriptions: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    createdAt?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `organizations.id`.<fk table='organizations' column='id'/>
     */
    organizationId?: number;
    /** Format: text */
    product?: string;
  };
  tasks: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    name?: string;
    /** Format: text */
    description?: string;
    /** Format: timestamp with time zone */
    dueDate?: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `profiles.id`.<fk table='profiles' column='id'/>
     */
    asignee?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `boardStates.id`.<fk table='boardStates' column='id'/>
     */
    stateId?: number;
  };
  teamMembers: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `teams.id`.<fk table='teams' column='id'/>
     */
    teamId?: number;
    /** Format: uuid */
    userId?: string;
  };
  teamRooms: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `teams.id`.<fk table='teams' column='id'/>
     */
    teamId?: number;
    /** Format: text */
    roomId?: string;
  };
  teams: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    createdAt?: string;
    /** Format: text */
    name?: string;
    /** Format: text */
    slug?: string;
    /** Format: text */
    description?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `organizations.id`.<fk table='organizations' column='id'/>
     */
    organizationId?: number;
  };
  votes: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    createdAt?: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `options.id`.<fk table='options' column='id'/>
     */
    optionId?: number;
    /** Format: uuid */
    userId?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description boardStates */
  "body.boardStates": definitions["boardStates"];
  /** Format: bigint */
  "rowFilter.boardStates.id": string;
  /** Format: bigint */
  "rowFilter.boardStates.boardId": string;
  /** Format: text */
  "rowFilter.boardStates.description": string;
  /** @description boards */
  "body.boards": definitions["boards"];
  /** Format: bigint */
  "rowFilter.boards.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.boards.created_at": string;
  /** Format: bigint */
  "rowFilter.boards.teamId": string;
  /** Format: text */
  "rowFilter.boards.name": string;
  /** @description chatMembers */
  "body.chatMembers": definitions["chatMembers"];
  /** Format: bigint */
  "rowFilter.chatMembers.id": string;
  /** Format: uuid */
  "rowFilter.chatMembers.userId": string;
  /** Format: bigint */
  "rowFilter.chatMembers.chatId": string;
  /** @description chats */
  "body.chats": definitions["chats"];
  /** Format: bigint */
  "rowFilter.chats.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.chats.createdAt": string;
  /** Format: boolean */
  "rowFilter.chats.isGroup": string;
  /** Format: text */
  "rowFilter.chats.name": string;
  /** Format: text */
  "rowFilter.chats.description": string;
  /** Format: text */
  "rowFilter.chats.thumbnail": string;
  /** Format: bigint */
  "rowFilter.chats.teamId": string;
  /** @description estimations */
  "body.estimations": definitions["estimations"];
  /** Format: bigint */
  "rowFilter.estimations.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.estimations.created_at": string;
  /** Format: bigint */
  "rowFilter.estimations.effort": string;
  /** Format: uuid */
  "rowFilter.estimations.userId": string;
  /** Format: text */
  "rowFilter.estimations.justification": string;
  /** Format: bigint */
  "rowFilter.estimations.taskId": string;
  /** @description initiatives */
  "body.initiatives": definitions["initiatives"];
  /** Format: bigint */
  "rowFilter.initiatives.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.initiatives.created_at": string;
  /** Format: text */
  "rowFilter.initiatives.title": string;
  /** Format: text */
  "rowFilter.initiatives.description": string;
  /** Format: text */
  "rowFilter.initiatives.content": string;
  /** Format: bigint */
  "rowFilter.initiatives.teamId": string;
  /** Format: timestamp with time zone */
  "rowFilter.initiatives.dueDate": string;
  /** Format: uuid */
  "rowFilter.initiatives.owner": string;
  /** Format: text */
  "rowFilter.initiatives.status": string;
  /** @description messages */
  "body.messages": definitions["messages"];
  /** Format: bigint */
  "rowFilter.messages.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.messages.createdAt": string;
  /** Format: text */
  "rowFilter.messages.text": string;
  /** Format: bigint */
  "rowFilter.messages.chatId": string;
  /** Format: uuid */
  "rowFilter.messages.userId": string;
  /** @description options */
  "body.options": definitions["options"];
  /** Format: bigint */
  "rowFilter.options.id": string;
  /** Format: bigint */
  "rowFilter.options.initiativeId": string;
  /** Format: text */
  "rowFilter.options.content": string;
  /** @description organizationInvitations */
  "body.organizationInvitations": definitions["organizationInvitations"];
  /** Format: bigint */
  "rowFilter.organizationInvitations.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.organizationInvitations.createdAt": string;
  /** Format: character varying */
  "rowFilter.organizationInvitations.userEmail": string;
  /** Format: bigint */
  "rowFilter.organizationInvitations.organizationId": string;
  /** @description organizationMembers */
  "body.organizationMembers": definitions["organizationMembers"];
  /** Format: bigint */
  "rowFilter.organizationMembers.id": string;
  /** Format: uuid */
  "rowFilter.organizationMembers.userId": string;
  /** Format: bigint */
  "rowFilter.organizationMembers.organizationId": string;
  /** @description organizations */
  "body.organizations": definitions["organizations"];
  /** Format: bigint */
  "rowFilter.organizations.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.organizations.createdAt": string;
  /** Format: text */
  "rowFilter.organizations.name": string;
  /** Format: text */
  "rowFilter.organizations.slug": string;
  /** Format: text */
  "rowFilter.organizations.logoUrl": string;
  /** Format: text */
  "rowFilter.organizations.description": string;
  /** Format: uuid */
  "rowFilter.organizations.ownerId": string;
  /** @description profiles */
  "body.profiles": definitions["profiles"];
  /** Format: uuid */
  "rowFilter.profiles.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.profiles.createdAt": string;
  /** Format: text */
  "rowFilter.profiles.email": string;
  /** Format: text */
  "rowFilter.profiles.firstName": string;
  /** Format: text */
  "rowFilter.profiles.lastName": string;
  /** @description subscriptions */
  "body.subscriptions": definitions["subscriptions"];
  /** Format: bigint */
  "rowFilter.subscriptions.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.subscriptions.createdAt": string;
  /** Format: bigint */
  "rowFilter.subscriptions.organizationId": string;
  /** Format: text */
  "rowFilter.subscriptions.product": string;
  /** @description tasks */
  "body.tasks": definitions["tasks"];
  /** Format: bigint */
  "rowFilter.tasks.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.tasks.created_at": string;
  /** Format: text */
  "rowFilter.tasks.name": string;
  /** Format: text */
  "rowFilter.tasks.description": string;
  /** Format: timestamp with time zone */
  "rowFilter.tasks.dueDate": string;
  /** Format: uuid */
  "rowFilter.tasks.asignee": string;
  /** Format: bigint */
  "rowFilter.tasks.stateId": string;
  /** @description teamMembers */
  "body.teamMembers": definitions["teamMembers"];
  /** Format: bigint */
  "rowFilter.teamMembers.id": string;
  /** Format: bigint */
  "rowFilter.teamMembers.teamId": string;
  /** Format: uuid */
  "rowFilter.teamMembers.userId": string;
  /** @description teamRooms */
  "body.teamRooms": definitions["teamRooms"];
  /** Format: bigint */
  "rowFilter.teamRooms.id": string;
  /** Format: bigint */
  "rowFilter.teamRooms.teamId": string;
  /** Format: text */
  "rowFilter.teamRooms.roomId": string;
  /** @description teams */
  "body.teams": definitions["teams"];
  /** Format: bigint */
  "rowFilter.teams.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.teams.createdAt": string;
  /** Format: text */
  "rowFilter.teams.name": string;
  /** Format: text */
  "rowFilter.teams.slug": string;
  /** Format: text */
  "rowFilter.teams.description": string;
  /** Format: bigint */
  "rowFilter.teams.organizationId": string;
  /** @description votes */
  "body.votes": definitions["votes"];
  /** Format: bigint */
  "rowFilter.votes.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.votes.createdAt": string;
  /** Format: bigint */
  "rowFilter.votes.optionId": string;
  /** Format: uuid */
  "rowFilter.votes.userId": string;
}

export interface operations {}

export interface external {}
